name: imageloader
description: A flutter project that demonstrates the use of dart isolates to download multiple images in parallel

# NEVER PUBLISH THIS(to https://pub.dev)!!!!!!!!!!!!
publish_to: 'none' 

# The version of the app this is to be released as.
version: 0.0.1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flash: ^3.0.5+2
  flutter_masonry_view: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

